#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=8
#SBATCH --constraint=cpu
#SBATCH --qos=debug
#SBATCH -J spectracl
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -t 00:30:00


# # Set up the Julia environment
# module purge; module load julia/1.10.4


for index in $(seq 1  1  16)
do 
    srun -n 1 julia --threads=1 Heisenberg_Disordered_$index.jl > Heisenberg_Disordered_$index.log &
done

wait