#!/bin/bash

for tmpJ2 in $(seq 0.00  0.05  0.75)
do
    mkdir J2_$tmpJ2
    cd J2_$tmpJ2
        cp ../Heisenberg_Dimerized_TEBD.jl Heisenberg_Dimerized_TEBD.jl
        # Linux version
        sed -i "s/J2=0.0/J2=$tmpJ2/g" Heisenberg_Dimerized_TEBD.jl
        # sed -i "s/delta=0.0/delta=$tmpDelta/g" Heisenberg_Dimerized_TEBD.jl
    
        # # MacOS version
        # sed -i "" "s/J2=0.0/J2=$tmpJ2/g" Heisenberg_Dimerized_TEBD.jl
        # sed -i "" "s/delta=0.0/delta=$tmpDelta/g" Heisenberg_Dimerized_TEBD.jl0
    cd ..
done

# Job Submission on Perlmutter
sbatch jobs_submission