#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=8
#SBATCH --constraint=cpu
#SBATCH --reservation=kitaev
#SBATCH -J spectracl
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -t 90:00:00


# # Set up the Julia environment
# module purge; module load julia/1.10.4


for J2 in $(seq 0.00  0.05  0.75)
do 
    cd /global/homes/x/xiaobo23/tensor_networks/spectral_function/J1_J2_Dimmerization/Delta0/J2_$J2
    srun -n 1 julia --threads=1 Heisenberg_Dimerized_TEBD.jl > spectral_J2_$J2.log &
done


wait